# Generated by Django 4.1.1 on 2022-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_topic_alter_post_options_post_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topics',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique_for_date='published'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
