# Generated by Django 4.1.1 on 2022-10-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='mail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
