# Generated by Django 4.1.1 on 2022-10-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_approve_comment_email_comment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(default='Plase enter email', max_length=100),
        ),
    ]
