# Generated by Django 4.1.1 on 2022-10-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_comment_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(default='Please enter email', max_length=100),
        ),
    ]
