# Generated by Django 4.1.1 on 2022-11-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_photo_contest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-submitted'], 'verbose_name': 'Photo Contest Submissions'},
        ),
    ]
